import { logger } from "./utils/logger";

logger.info("Ranger Delta-Neutral Vault Strategy");
logger.info("====================================");
logger.info("");
logger.info("Core Commands:");
logger.info("  npm run agent              — Start the AI strategy agent");
logger.info("  npm run dashboard          — Live monitoring dashboard");
logger.info("  npm run backtest           — Run historical backtest");
logger.info("");
logger.info("Vault Management:");
logger.info("  npm run vault:init         — Initialize Ranger Earn vault");
logger.info("  npm run vault:deposit      — Deposit USDC into vault");
logger.info("  npm run vault:withdraw     — Withdraw from vault");
logger.info("  npm run vault:status       — Check vault status");
logger.info("  npm run drift:status       — Check Drift account & vault status");
logger.info("  npm run drift:init-vault   — Create Drift vault for delegate trading");
logger.info("");
logger.info("Devnet Testing:");
logger.info("  npm run devnet:setup       — Set up devnet wallet and airdrop");
logger.info("  npm run devnet:strategy    — Run strategy cycle on devnet");
logger.info("  npm run devnet:dry-run     — Dry-run without execution");
logger.info("  npm run devnet:cleanup     — Close all devnet positions");
logger.info("  npm run devnet:llm-test    — Test LLM strategy advisor");
logger.info("");
logger.info("Deployment:");
logger.info("  npm run launch:preflight   — Mainnet launch preflight checks");
logger.info("  npm run export-trades      — Export trade history for submission");
logger.info("");
